

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentApp
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StudentsEntities : DbContext
{
    public StudentsEntities()
        : base("name=StudentsEntities")
    {

    }

    public virtual DbSet<StudentDb> StudentDb { get; set; }

}

}

