
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentApp
{

using System;
    using System.Collections.Generic;
    
public partial class StudentDb
{

    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime BirthDate { get; set; }

}

}
